### ISSUE TITLE
Not compatible with custom biomes

### ISSUE THREAD

**Issue by NeumimTo** [itsmiir/atlas#6]
Im trying to combine atlas with some custom biomes from william wythers datapack. 

It seems like atlas has some problems to generate custom biomes properly.

[testpack.zip](https://github.com/itsmiir/atlas/files/10892472/testpack.zip)

Custom biome in atlas dimmension:

![2023-03-04_12 46 42](https://user-images.githubusercontent.com/4391346/222976761-e4e643e1-96ab-4e71-ac88-e2046ce923c6.png)

the very same biome in vanilla overworld: 

![2023-03-04_12 47 33](https://user-images.githubusercontent.com/4391346/222976799-36088247-4aeb-42ea-9d8b-2222062d450d.png)

**Comment by itsmiir** [comment]
seems to be that you didn't update the surface rule; my guess is that WWOO changes the surface rule to add those features.
